simplified_poisoning_labels = {
  "Poisoning: Other synthetic narcotics": "Synthetic opioids (incl. fentanyl)",
  "Poisoning: Psychostimulants with abuse potential": "Psychostimulants (meth, amphetamines)",
  "Poisoning: Other and unspecified drugs, medicaments and biological substances": "Other/unspecified drugs",
  "Poisoning: Cocaine": "Cocaine",
  "Toxic effect: Ethanol": "Alcohol (ethanol)",
  "Poisoning: Benzodiazepines": "Benzodiazepines",
  "Poisoning: Other opioids": "Natural/semisynthetic opioids (e.g. oxycodone)",
  "Poisoning: Antiepileptic and sedative-hypnotic drugs, unspecified": "Antiseizure & sedative drugs (unspecified)",
  "Poisoning: Other antiepileptic and sedative-hypnotic drugs": "Antiseizure & sedative drugs (other)",
  "Poisoning: Methadone": "Methadone",
  "Poisoning: Heroin": "Heroin",
  "Poisoning: Other and unspecified antidepressants": "Antidepressants (other)",
  "Toxic effect: Alcohol, unspecified": "Alcohol (unspecified)",
  "Poisoning: Antiallergic and antiemetic drugs": "Antihistamines & anti-nausea drugs",
  "Poisoning: Other and unspecified antipsychotics and neuroleptics": "Antipsychotics (other)"
}

simplified_cancer_labels = {
	"Malignant neoplasms of meninges, brain and other parts of central nervous system": "Brain & CNS",
	"All other and unspecified malignant neoplasms": "Other & unspecified",
	"Malignant neoplasms of liver and intrahepatic bile ducts": "Liver & bile duct",
	"Malignant neoplasm of esophagus": "Esophagus",
	"Non-Hodgkin lymphoma": "Non-Hodgkin lymphoma",
	"Malignant neoplasm of ovary": "Ovary",
	"Malignant neoplasms of trachea, bronchus and lung": "Lung",
	"Malignant neoplasms of lip, oral cavity and pharynx": "Mouth & throat",
	"Malignant neoplasms of colon, rectum and anus": "Colorectal & anal",
	"Malignant melanoma of skin": "Melanoma",
	"Malignant neoplasms of corpus uteri and uterus, part unspecified": "Uterus (excl. cervix)",
	"Leukemia": "Leukemia",
	"Malignant neoplasm of stomach": "Stomach",
	"Malignant neoplasm of breast": "Breast",
	"Malignant neoplasm of prostate": "Prostate",
	"Malignant neoplasms of kidney and renal pelvis": "Kidney",
	"Malignant neoplasm of pancreas": "Pancreas",
	"Malignant neoplasm of bladder": "Bladder"
}

simplified_accident_labels = {
	"Motor vehicle accidents": "Motor vehicle crashes",
	"Accidental poisoning and exposure to noxious substances": "Poisoning",
	"Other and unspecified nontransport accidents and their sequelae": "Other nontransport accidents",
	"Accidental drowning and submersion": "Drowning",
	"Falls": "Falls",
	"Water, air and space, and other and unspecified transport accidents and their sequelae": "Water, air & other transport",
	"Other land transport accidents": "Other land transport",
	"Accidental exposure to smoke, fire and flames": "Fire and smoke",
	"Accidental discharge of firearms": "Accidental firearm deaths"
}

simplified_rankable_subset_label = {
	"Salmonella infections": "Salmonella infections",
	"Shigellosis and amebiasis": "Shigellosis and amebiasis",
	"Tuberculosis": "Tuberculosis",
	"Whooping cough": "Whooping cough",
	"Scarlet fever and erysipelas": "Scarlet fever and erysipelas",
	"Meningococcal infection": "Meningococcal infection",
	"Septicemia": "Sepsis",
	"Syphilis": "Syphilis",
	"Acute poliomyelitis": "Polio",
	"Arthropod-borne viral encephalitis": "Mosquito/tick-borne encephalitis",
	"Measles": "Measles",
	"Viral hepatitis": "Viral hepatitis",
	"Human immunodeficiency virus (HIV) disease": "HIV",
	"Malaria": "Malaria",
	"Malignant neoplasms": "Cancer",
	"In situ neoplasms, benign neoplasms and neoplasms of uncertain or unknown behavior": "Non-malignant tumors",
	"Anemias": "Anemia",
	"Diabetes mellitus": "Diabetes",
	"Nutritional deficiencies": "Nutritional deficiencies",
	"Meningitis": "Meningitis",
	"Parkinson disease": "Parkinson's",
	"Alzheimer disease": "Alzheimer's",
	"Diseases of heart": "Heart disease",
	"Essential hypertension and hypertensive renal disease": "Hypertensive disease",
	"Cerebrovascular diseases": "Stroke",
	"Atherosclerosis": "Atherosclerosis",
	"Aortic aneurysm and dissection": "Aortic aneurysm/dissection",
	"Influenza and pneumonia": "Flu and pneumonia",
	"Acute bronchitis and bronchiolitis": "Acute bronchitis/bronchiolitis",
	"Chronic lower respiratory diseases": "Chronic lung disease",
	"Pneumoconioses and chemical effects": "Dust and chemical lung disease",
	"Pneumonitis due to solids and liquids": "Aspiration pneumonia",
	"Peptic ulcer": "Peptic ulcer",
	"Diseases of appendix": "Appendicitis",
	"Hernia": "Hernia",
	"Chronic liver disease and cirrhosis": "Liver disease",
	"Cholelithiasis and other disorders of gallbladder": "Gallbladder disease",
	"Nephritis, nephrotic syndrome and nephrosis": "Kidney disease",
	"Infections of kidney": "Kidney infection",
	"Hyperplasia of prostate": "Enlarged prostate",
	"Inflammatory diseases of female pelvic organs": "Pelvic inflammatory disease",
	"Pregnancy, childbirth and the puerperium": "Pregnancy and childbirth",
	"Certain conditions originating in the perinatal period": "Perinatal conditions",
	"Congenital malformations, deformations and chromosomal abnormalities": "Birth defects",
	"Accidents (unintentional injuries)": "Accidents",
	"Intentional self-harm (suicide)": "Suicide",
	"Assault (homicide)": "Homicide",
	"Legal intervention": "Legal intervention",
	"Operations of war and their sequelae": "War",
	"Complications of medical and surgical care": "Medical and surgical complications",
	"Enterocolitis due to Clostridium difficile": "C. difficile infection",
	"COVID-19": "COVID-19"
}